name: deploy-auth

on: 
  push: 
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t denzik10/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push denzik10/auth
