name: deploy-auth

on: 
  push: 
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t denzik10/auth .
#       -
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env: 
          DOCKER_USERNAME: ${{ DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ DOCKER_PASSWORD }}  
      - run: docker push denzik10/auth
