name: deploy-auth

on: 
  push: 
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The DOCKER_USERNAME is:${{secrets.DOCKER_USERNAME}}"
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: cd auth && docker build -t denzik10/auth .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push denzik10/auth
