name: deploy-auth

on: 
  push: 
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    -  
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t denzik10/auth .
      - run: docker push denzik10/auth
